# Generated by Django 5.2.7 on 2025-10-14 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 12, 17, 40, 668371, tzinfo=datetime.timezone.utc)),
        ),
    ]
