# Generated by Django 5.2.7 on 2025-10-20 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 20, 7, 56, 11, 72011, tzinfo=datetime.timezone.utc)),
        ),
    ]
