# Generated by Django 5.2.7 on 2025-10-21 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(choices=[('campus', 'Campus'), ('outside', 'Outside')], default='campus', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 21, 13, 2, 59, 311504, tzinfo=datetime.timezone.utc)),
        ),
    ]
